// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: findnearby.proto

package com.hivewallet.androidclient.wallet;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ContactOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version_major = 1;
    /**
     * <code>required int32 version_major = 1;</code>
     */
    boolean hasVersionMajor();
    /**
     * <code>required int32 version_major = 1;</code>
     */
    int getVersionMajor();

    // optional int32 version_minor = 2 [default = 0];
    /**
     * <code>optional int32 version_minor = 2 [default = 0];</code>
     */
    boolean hasVersionMinor();
    /**
     * <code>optional int32 version_minor = 2 [default = 0];</code>
     */
    int getVersionMinor();

    // required string bitcoin_address = 3;
    /**
     * <code>required string bitcoin_address = 3;</code>
     */
    boolean hasBitcoinAddress();
    /**
     * <code>required string bitcoin_address = 3;</code>
     */
    java.lang.String getBitcoinAddress();
    /**
     * <code>required string bitcoin_address = 3;</code>
     */
    com.google.protobuf.ByteString
        getBitcoinAddressBytes();

    // optional string name = 4;
    /**
     * <code>optional string name = 4;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional bytes photo = 5;
    /**
     * <code>optional bytes photo = 5;</code>
     */
    boolean hasPhoto();
    /**
     * <code>optional bytes photo = 5;</code>
     */
    com.google.protobuf.ByteString getPhoto();
  }
  /**
   * Protobuf type {@code findnearby.Contact}
   */
  public static final class Contact extends
      com.google.protobuf.GeneratedMessage
      implements ContactOrBuilder {
    // Use Contact.newBuilder() to construct.
    private Contact(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Contact(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Contact defaultInstance;
    public static Contact getDefaultInstance() {
      return defaultInstance;
    }

    public Contact getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Contact(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              versionMajor_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              versionMinor_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              bitcoinAddress_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              name_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              photo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hivewallet.androidclient.wallet.Protos.internal_static_findnearby_Contact_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hivewallet.androidclient.wallet.Protos.internal_static_findnearby_Contact_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hivewallet.androidclient.wallet.Protos.Contact.class, com.hivewallet.androidclient.wallet.Protos.Contact.Builder.class);
    }

    public static com.google.protobuf.Parser<Contact> PARSER =
        new com.google.protobuf.AbstractParser<Contact>() {
      public Contact parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Contact(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Contact> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 version_major = 1;
    public static final int VERSION_MAJOR_FIELD_NUMBER = 1;
    private int versionMajor_;
    /**
     * <code>required int32 version_major = 1;</code>
     */
    public boolean hasVersionMajor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version_major = 1;</code>
     */
    public int getVersionMajor() {
      return versionMajor_;
    }

    // optional int32 version_minor = 2 [default = 0];
    public static final int VERSION_MINOR_FIELD_NUMBER = 2;
    private int versionMinor_;
    /**
     * <code>optional int32 version_minor = 2 [default = 0];</code>
     */
    public boolean hasVersionMinor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 version_minor = 2 [default = 0];</code>
     */
    public int getVersionMinor() {
      return versionMinor_;
    }

    // required string bitcoin_address = 3;
    public static final int BITCOIN_ADDRESS_FIELD_NUMBER = 3;
    private java.lang.Object bitcoinAddress_;
    /**
     * <code>required string bitcoin_address = 3;</code>
     */
    public boolean hasBitcoinAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string bitcoin_address = 3;</code>
     */
    public java.lang.String getBitcoinAddress() {
      java.lang.Object ref = bitcoinAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bitcoinAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bitcoin_address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBitcoinAddressBytes() {
      java.lang.Object ref = bitcoinAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bitcoinAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 4;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes photo = 5;
    public static final int PHOTO_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString photo_;
    /**
     * <code>optional bytes photo = 5;</code>
     */
    public boolean hasPhoto() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes photo = 5;</code>
     */
    public com.google.protobuf.ByteString getPhoto() {
      return photo_;
    }

    private void initFields() {
      versionMajor_ = 0;
      versionMinor_ = 0;
      bitcoinAddress_ = "";
      name_ = "";
      photo_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersionMajor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBitcoinAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, versionMajor_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, versionMinor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBitcoinAddressBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, photo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, versionMajor_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, versionMinor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBitcoinAddressBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, photo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hivewallet.androidclient.wallet.Protos.Contact parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hivewallet.androidclient.wallet.Protos.Contact parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hivewallet.androidclient.wallet.Protos.Contact parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hivewallet.androidclient.wallet.Protos.Contact parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hivewallet.androidclient.wallet.Protos.Contact parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hivewallet.androidclient.wallet.Protos.Contact parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hivewallet.androidclient.wallet.Protos.Contact parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hivewallet.androidclient.wallet.Protos.Contact parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hivewallet.androidclient.wallet.Protos.Contact parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hivewallet.androidclient.wallet.Protos.Contact parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hivewallet.androidclient.wallet.Protos.Contact prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code findnearby.Contact}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hivewallet.androidclient.wallet.Protos.ContactOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hivewallet.androidclient.wallet.Protos.internal_static_findnearby_Contact_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hivewallet.androidclient.wallet.Protos.internal_static_findnearby_Contact_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hivewallet.androidclient.wallet.Protos.Contact.class, com.hivewallet.androidclient.wallet.Protos.Contact.Builder.class);
      }

      // Construct using com.hivewallet.androidclient.wallet.Protos.Contact.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        versionMajor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        versionMinor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        bitcoinAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        photo_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hivewallet.androidclient.wallet.Protos.internal_static_findnearby_Contact_descriptor;
      }

      public com.hivewallet.androidclient.wallet.Protos.Contact getDefaultInstanceForType() {
        return com.hivewallet.androidclient.wallet.Protos.Contact.getDefaultInstance();
      }

      public com.hivewallet.androidclient.wallet.Protos.Contact build() {
        com.hivewallet.androidclient.wallet.Protos.Contact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hivewallet.androidclient.wallet.Protos.Contact buildPartial() {
        com.hivewallet.androidclient.wallet.Protos.Contact result = new com.hivewallet.androidclient.wallet.Protos.Contact(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.versionMajor_ = versionMajor_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.versionMinor_ = versionMinor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bitcoinAddress_ = bitcoinAddress_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.photo_ = photo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hivewallet.androidclient.wallet.Protos.Contact) {
          return mergeFrom((com.hivewallet.androidclient.wallet.Protos.Contact)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hivewallet.androidclient.wallet.Protos.Contact other) {
        if (other == com.hivewallet.androidclient.wallet.Protos.Contact.getDefaultInstance()) return this;
        if (other.hasVersionMajor()) {
          setVersionMajor(other.getVersionMajor());
        }
        if (other.hasVersionMinor()) {
          setVersionMinor(other.getVersionMinor());
        }
        if (other.hasBitcoinAddress()) {
          bitField0_ |= 0x00000004;
          bitcoinAddress_ = other.bitcoinAddress_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000008;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPhoto()) {
          setPhoto(other.getPhoto());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersionMajor()) {
          
          return false;
        }
        if (!hasBitcoinAddress()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hivewallet.androidclient.wallet.Protos.Contact parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hivewallet.androidclient.wallet.Protos.Contact) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version_major = 1;
      private int versionMajor_ ;
      /**
       * <code>required int32 version_major = 1;</code>
       */
      public boolean hasVersionMajor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version_major = 1;</code>
       */
      public int getVersionMajor() {
        return versionMajor_;
      }
      /**
       * <code>required int32 version_major = 1;</code>
       */
      public Builder setVersionMajor(int value) {
        bitField0_ |= 0x00000001;
        versionMajor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version_major = 1;</code>
       */
      public Builder clearVersionMajor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        versionMajor_ = 0;
        onChanged();
        return this;
      }

      // optional int32 version_minor = 2 [default = 0];
      private int versionMinor_ ;
      /**
       * <code>optional int32 version_minor = 2 [default = 0];</code>
       */
      public boolean hasVersionMinor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 version_minor = 2 [default = 0];</code>
       */
      public int getVersionMinor() {
        return versionMinor_;
      }
      /**
       * <code>optional int32 version_minor = 2 [default = 0];</code>
       */
      public Builder setVersionMinor(int value) {
        bitField0_ |= 0x00000002;
        versionMinor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version_minor = 2 [default = 0];</code>
       */
      public Builder clearVersionMinor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        versionMinor_ = 0;
        onChanged();
        return this;
      }

      // required string bitcoin_address = 3;
      private java.lang.Object bitcoinAddress_ = "";
      /**
       * <code>required string bitcoin_address = 3;</code>
       */
      public boolean hasBitcoinAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string bitcoin_address = 3;</code>
       */
      public java.lang.String getBitcoinAddress() {
        java.lang.Object ref = bitcoinAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bitcoinAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bitcoin_address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBitcoinAddressBytes() {
        java.lang.Object ref = bitcoinAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bitcoinAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bitcoin_address = 3;</code>
       */
      public Builder setBitcoinAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bitcoinAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bitcoin_address = 3;</code>
       */
      public Builder clearBitcoinAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bitcoinAddress_ = getDefaultInstance().getBitcoinAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string bitcoin_address = 3;</code>
       */
      public Builder setBitcoinAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bitcoinAddress_ = value;
        onChanged();
        return this;
      }

      // optional string name = 4;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 4;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }

      // optional bytes photo = 5;
      private com.google.protobuf.ByteString photo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes photo = 5;</code>
       */
      public boolean hasPhoto() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes photo = 5;</code>
       */
      public com.google.protobuf.ByteString getPhoto() {
        return photo_;
      }
      /**
       * <code>optional bytes photo = 5;</code>
       */
      public Builder setPhoto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        photo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes photo = 5;</code>
       */
      public Builder clearPhoto() {
        bitField0_ = (bitField0_ & ~0x00000010);
        photo_ = getDefaultInstance().getPhoto();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:findnearby.Contact)
    }

    static {
      defaultInstance = new Contact(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:findnearby.Contact)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_findnearby_Contact_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_findnearby_Contact_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020findnearby.proto\022\nfindnearby\"p\n\007Contac" +
      "t\022\025\n\rversion_major\030\001 \002(\005\022\030\n\rversion_mino" +
      "r\030\002 \001(\005:\0010\022\027\n\017bitcoin_address\030\003 \002(\t\022\014\n\004n" +
      "ame\030\004 \001(\t\022\r\n\005photo\030\005 \001(\014B-\n#com.hivewall" +
      "et.androidclient.walletB\006Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_findnearby_Contact_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_findnearby_Contact_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_findnearby_Contact_descriptor,
              new java.lang.String[] { "VersionMajor", "VersionMinor", "BitcoinAddress", "Name", "Photo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
